services:
  desktop:
    privileged: true
    tty: true
    stdin_open: true
    shm_size: 16g
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    expose:
      - "22" #ssh
      - "4000" #nomachine
      - "5900" #vnc
      - "6080" #novnc
    ports:
      - "10022:22" #ssh
      - "14000:4000" #nomachine
      - "5901:5900" #vnc
      - "6081:6080" #novnc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
              # device_ids: ['0', '3']
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      - HF_DATASETS_OFFLINE=1
    # command: ["/bin/bash", "/scripts/startup.sh", "bash"]
    volumes:
      - ${PWD}:/opt/vln_platform
      - ${DATA_PATH}:/opt/vln_platform/data