services:
  desktop:
    image: streamvln:v1
    container_name: streamvln
    build:
      context: .
      dockerfile: Dockerfile_streamvln
      args:
        - BASE_IMAGE=pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel